SELECT
    CUSTOMERS.CUSTOMER_ID AS CUSTOMER_ID,
    CUSTOMERS.NAME AS CUSTOMER_NAME,
    COUNT(*) AS ORDER_COUNT,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM ORDERS
INNER JOIN SYSTEM.CUSTOMERERRORS CUSTOMERS on ORDERS.CUSTOMER_ID = customers.CUSTOMER_ID
WHERE CUSTOMERS.CUSTOMER_ID = 16
GROUP BY CUSTOMERS.NAME, CUSTOMERS.CUSTOMER_ID
ORDER BY CUSTOMERS.CUSTOMER_ID;


SELECT
    CUSTOMER_ID,
    NAME,
    UTL_MATCH.JARO_WINKLER_SIMILARITY('Kaneel Dias', NAME) AS JARO_WINKLER_SCORE,
    UTL_MATCH.EDIT_DISTANCE_SIMILARITY('Kaneel Dias', NAME) AS EDIT_DISTANCE_SCORE
FROM SYSTEM.CUSTOMERERRORS
WHERE CUSTOMER_ID != 16
ORDER BY JARO_WINKLER_SCORE DESC;

SELECT
    CUSTOMERS.CUSTOMER_ID AS CUSTOMER_ID,
    CUSTOMERS.NAME AS CUSTOMER_NAME,
    COUNT(*) AS ORDER_COUNT,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM ORDERS
INNER JOIN SYSTEM.CUSTOMERERRORS CUSTOMERS on ORDERS.CUSTOMER_ID = customers.CUSTOMER_ID
WHERE CUSTOMERS.CUSTOMER_ID IN (
    SELECT CUSTOMER_ID
    FROM CUSTOMERERRORS
    WHERE UTL_MATCH.JARO_WINKLER_SIMILARITY('Kaneel Dias', NAME) > 75 AND
          UTL_MATCH.EDIT_DISTANCE_SIMILARITY('Kaneel Dias', NAME) > 50 AND
          CUSTOMER_ID != 16
)
GROUP BY CUSTOMERS.NAME, CUSTOMERS.CUSTOMER_ID
ORDER BY CUSTOMERS.CUSTOMER_ID;

UPDATE ORDERS
SET CUSTOMER_ID = 16
WHERE CUSTOMER_ID IN (
    SELECT CUSTOMER_ID
    FROM CUSTOMERERRORS
    WHERE UTL_MATCH.JARO_WINKLER_SIMILARITY('Kaneel Dias', NAME) > 75 AND
          UTL_MATCH.EDIT_DISTANCE_SIMILARITY('Kaneel Dias', NAME) > 50 AND
          CUSTOMER_ID != 16
);

DELETE FROM CUSTOMERERRORS
WHERE CUSTOMER_ID IN (
    SELECT CUSTOMER_ID
    FROM CUSTOMERERRORS
    WHERE UTL_MATCH.JARO_WINKLER_SIMILARITY('Kaneel Dias', NAME) > 75 AND
          UTL_MATCH.EDIT_DISTANCE_SIMILARITY('Kaneel Dias', NAME) > 50 AND
          CUSTOMER_ID != 16
);
